services:
  free-games-claimer:
    image: ghcr.io/vogler/free-games-claimer:latest
    container_name: free-games-claimer
    volumes:
      - ./fgc-data:/fgc/data
    environment:
      # Configuraciones opcionales (1=activar, 0=desactivar)
      - CLAIM_EPIC=1
      - CLAIM_PRIME=1
      - CLAIM_GOG=1
      - NOTIFY=1
      - SHOW_BROWSER=0 # Desactiva el visor VNC
    ports:
      # Puerto para VNC en caso de querer ver el navegador headless para resolver captchas iniciales
      - "127.0.0.1:5900:5900"
      - "127.0.0.1:6080:6080"
    restart: unless-stopped
